name: hello-world
on:
  workflow_call:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  call-workflow-passing-data2:
    uses: ./.github/workflows/reusable-workflow2.yml
